server:
  port: 8081


person:
  name: dulu
  email: aries_cy@163.com
  age: 16
  boss: true
  birth: 2016/5/6
  maps: {k1: v1,k2: 12}
  lists:
    - zhangsan
    - lisi
  dog:
    name: 旺财
    age: 2


user: 张三